use chacha20poly1305::{
    aead::{AeadMutInPlace, KeySizeUser},
    ChaCha20Poly1305,
};
use digest::{
    core_api::BlockSizeUser, generic_array::ArrayLength, Digest, FixedOutput, OutputSizeUser, Reset,
};
use sha2::Sha256;
use typenum::{Sum, U22};

/// Represents a TLS 1.3 cipher suite
#[derive(Copy, Clone, Debug, defmt::Format)]
pub enum CipherSuite {
    // TlsAes128GcmSha256 = 0x1301,
    // TlsAes256GcmSha384 = 0x1302,
    // TlsChacha20Poly1305Sha256 = 0x1303,
    // TlsAes128CcmSha256 = 0x1304,
    // TlsAes128Ccm8Sha256 = 0x1305,
    // TlsPskAes128GcmSha256 = 0x00A8,
    TlsEcdhePskWithChacha20Poly1305Sha256 = 0xCCAC,
}

impl CipherSuite {
    pub fn of(num: u16) -> Option<Self> {
        match num {
            // 0x1301 => Some(Self::TlsAes128GcmSha256),
            // 0x1302 => Some(Self::TlsAes256GcmSha384),
            // 0x1303 => Some(Self::TlsChacha20Poly1305Sha256),
            // 0x1304 => Some(Self::TlsAes128CcmSha256),
            // 0x1305 => Some(Self::TlsAes128Ccm8Sha256),
            // 0x00A8 => Some(Self::TlsPskAes128GcmSha256),
            // 0xCC,0xAB	TLS_PSK_WITH_CHACHA20_POLY1305_SHA256
            0xCCAC => Some(Self::TlsEcdhePskWithChacha20Poly1305Sha256),
            _ => None,
        }
    }
}

type HashSize<CipherSuite> = <<CipherSuite as TlsCipherSuite>::Hash as OutputSizeUser>::OutputSize;
// Max length of a label is:
// - length: 2
// - label: 1 + 18
// - context: 1 + hash length
// = 22 + hash length
type LabelSize<CipherSuite> = Sum<HashSize<CipherSuite>, U22>;

/// Defines cipher and hash to use for as crypto suite.
pub trait TlsCipherSuite {
    /// The code point as defined in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml
    const CODE_POINT: u16;

    /// Cipher to use with this cipher suite.
    type Cipher: AeadMutInPlace + KeySizeUser;

    /// The hash to use with this cipher suite.
    type Hash: Digest + Reset + Clone + OutputSizeUser + BlockSizeUser + FixedOutput;

    /// The size of the hash generated by `Self::Hash`.
    type HashDigestSize: ArrayLength<u8>;

    /// The size of the HKDF label buffer, use to get the correct size.
    type LabelBufferSize: ArrayLength<u8>;
}

/// Chacha chipher.
pub struct TlsEcdhePskWithChacha20Poly1305Sha256;

impl TlsCipherSuite for TlsEcdhePskWithChacha20Poly1305Sha256 {
    const CODE_POINT: u16 = CipherSuite::TlsEcdhePskWithChacha20Poly1305Sha256 as u16;

    type Cipher = ChaCha20Poly1305;
    type Hash = Sha256;

    type HashDigestSize = HashSize<Self>;
    type LabelBufferSize = LabelSize<Self>;
}
